java_binary(
    name = "runner",
    srcs = ["Runner.java"],
    main_class = "com.example.cmdline.Runner",
    deps = ["//:greeter",
            "@maven//:org_apache_lucene_lucene_core",
            "@maven//:org_apache_lucene_lucene_codecs"
            ],
)
